title: TPMC Documentation
description: Documentation for the Team Project Cluj Mannheim 2020
theme: jekyll-theme-cayman
github:
 documentation_start: https://d067659.github.io/tpmc_documentation/technical_documentation/overall_microservice_archtitecture.html
 evaluation_start: https://d067659.github.io/tpmc_documentation/evaluation/use_case_based_evaluation_process.html
 welcome_start: https://d067659.github.io/tpmc_documentation/
